package com.example.springbootMYBATIS.mapper;

import com.example.springbootMYBATIS.model.Employees;
import com.example.springbootMYBATIS.model.EmployeesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	long countByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	int deleteByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	int deleteByPrimaryKey(Long employeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	int insert(Employees record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	int insertSelective(Employees record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	List<Employees> selectByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	Employees selectByPrimaryKey(Long employeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	int updateByExampleSelective(@Param("record") Employees record, @Param("example") EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	int updateByExample(@Param("record") Employees record, @Param("example") EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	int updateByPrimaryKeySelective(Employees record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	int updateByPrimaryKey(Employees record);
}