package com.example.springbootMYBATIS.model;

public class Employees {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.employee_id
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	private Long employeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.first_name
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.last_name
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.version
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	private Integer version;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.employee_id
	 * @return  the value of employees.employee_id
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	public Long getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.employee_id
	 * @param employeeId  the value for employees.employee_id
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.first_name
	 * @return  the value of employees.first_name
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.first_name
	 * @param firstName  the value for employees.first_name
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.last_name
	 * @return  the value of employees.last_name
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.last_name
	 * @param lastName  the value for employees.last_name
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.version
	 * @return  the value of employees.version
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.version
	 * @param version  the value for employees.version
	 * @mbg.generated  Fri Jun 07 15:36:42 IST 2019
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}
}